### ISSUE TITLE
Any tricks to avoid overfitting?

### ISSUE THREAD

**Issue by Pamikk** [lsvih/Sliding-Convolution#2]
训练集上准确率差不多到90多了，测试集还只有50多orz...

**Comment by lsvih** [comment]
@snilloO 你好，事实上这个问题并不好解决，因为模型参数相对于我们用的 IIIT5K 数据集（2000 个训练样本）过于多了。不过您可以参考 https://github.com/bgshih/crnn/issues/5#issuecomment-202773208 的评测方法。

**Comment by Pamikk** [comment]
十分感谢，准备换个backbone再换个数据集再试试...
